"""Initial CRM Schema

Revision ID: 0e7dcb13e642
Revises:
Create Date: 2026-07-30 12:34:25.602627+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7dcb13e642'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration's schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SALES_MANAGER', 'SALES_AGENT', name='user_role'), server_default='SALES_AGENT', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('preferred_location', sa.String(length=255), nullable=True),
    sa.Column('bhk', sa.String(length=20), nullable=True),
    sa.Column('lead_source', sa.Enum('WEBSITE', 'WALK_IN', 'FACEBOOK', 'INSTAGRAM', 'MAGICBRICKS', 'NOBROKER', 'REFERRAL', 'PHONE', 'OTHER', name='lead_source'), server_default='OTHER', nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'SITE_VISIT', 'NEGOTIATION', 'BOOKED', 'LOST', name='lead_status'), server_default='NEW', nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='lead_priority'), server_default='MEDIUM', nullable=False),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('next_follow_up', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], name=op.f('fk_leads_assigned_agent_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_leads_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_assigned_agent_id'), 'leads', ['assigned_agent_id'], unique=False)
    op.create_index('ix_leads_assigned_agent_id_status', 'leads', ['assigned_agent_id', 'status'], unique=False)
    op.create_index(op.f('ix_leads_created_by'), 'leads', ['created_by'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_full_name'), 'leads', ['full_name'], unique=False)
    op.create_index(op.f('ix_leads_lead_source'), 'leads', ['lead_source'], unique=False)
    op.create_index(op.f('ix_leads_next_follow_up'), 'leads', ['next_follow_up'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_priority'), 'leads', ['priority'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index('ix_leads_status_priority', 'leads', ['status', 'priority'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('property_code', sa.String(length=32), nullable=False, comment='Human-readable unique code, e.g. PROP-2026-00001'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_type', sa.Enum('apartment', 'villa', 'independent_house', 'plot', 'commercial_office', 'commercial_shop', 'warehouse', 'agricultural_land', 'penthouse', 'studio', name='property_type_enum'), nullable=False),
    sa.Column('property_status', sa.Enum('available', 'under_negotiation', 'sold', 'rented', 'on_hold', 'withdrawn', name='property_status_enum'), server_default='available', nullable=False),
    sa.Column('listing_type', sa.Enum('sale', 'rent', name='listing_type_enum'), nullable=False),
    sa.Column('furnishing', sa.Enum('furnished', 'semi_furnished', 'unfurnished', name='furnishing_type_enum'), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False, comment='Sale price or monthly/annual rent depending on listing_type'),
    sa.Column('area_sqft', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('parking', sa.Integer(), server_default='0', nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=150), nullable=False),
    sa.Column('owner_phone', sa.String(length=20), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('area_sqft > 0', name=op.f('ck_properties_ck_properties_area_sqft_positive')),
    sa.CheckConstraint('bathrooms IS NULL OR bathrooms >= 0', name=op.f('ck_properties_ck_properties_bathrooms_non_negative')),
    sa.CheckConstraint('bedrooms IS NULL OR bedrooms >= 0', name=op.f('ck_properties_ck_properties_bedrooms_non_negative')),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name=op.f('ck_properties_ck_properties_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name=op.f('ck_properties_ck_properties_longitude_range')),
    sa.CheckConstraint('parking IS NULL OR parking >= 0', name=op.f('ck_properties_ck_properties_parking_non_negative')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_properties_ck_properties_price_non_negative')),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], name=op.f('fk_properties_assigned_agent_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties'))
    )
    op.create_index('ix_properties_active_featured', 'properties', ['is_active', 'is_featured'], unique=False)
    op.create_index(op.f('ix_properties_assigned_agent_id'), 'properties', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index('ix_properties_city_state', 'properties', ['city', 'state'], unique=False)
    op.create_index(op.f('ix_properties_is_active'), 'properties', ['is_active'], unique=False)
    op.create_index(op.f('ix_properties_listing_type'), 'properties', ['listing_type'], unique=False)
    op.create_index(op.f('ix_properties_pincode'), 'properties', ['pincode'], unique=False)
    op.create_index('ix_properties_price', 'properties', ['price'], unique=False)
    op.create_index(op.f('ix_properties_property_code'), 'properties', ['property_code'], unique=True)
    op.create_index(op.f('ix_properties_property_status'), 'properties', ['property_status'], unique=False)
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_state'), 'properties', ['state'], unique=False)
    op.create_index('ix_properties_type_status_listing', 'properties', ['property_type', 'property_status', 'listing_type'], unique=False)
    op.create_index(op.f('ix_properties_uuid'), 'properties', ['uuid'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='customer_gender_enum'), nullable=True),
    sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'OTHER', name='customer_marital_status_enum'), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('annual_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=14), nullable=True),
    sa.Column('passport_number', sa.String(length=20), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('preferred_city', sa.String(length=100), nullable=True),
    sa.Column('preferred_area', sa.String(length=150), nullable=True),
    sa.Column('preferred_property_type', sa.Enum('APARTMENT', 'VILLA', 'INDEPENDENT_HOUSE', 'PLOT', 'COMMERCIAL', 'OFFICE_SPACE', 'WAREHOUSE', 'OTHER', name='customer_preferred_property_type_enum'), nullable=True),
    sa.Column('preferred_bhk', sa.Enum('STUDIO', 'ONE_BHK', 'TWO_BHK', 'THREE_BHK', 'FOUR_BHK', 'FIVE_PLUS_BHK', name='customer_preferred_bhk_enum'), nullable=True),
    sa.Column('customer_type', sa.Enum('BUYER', 'SELLER', 'TENANT', 'LANDLORD', 'INVESTOR', name='customer_type_enum'), server_default='BUYER', nullable=False),
    sa.Column('customer_source', sa.Enum('WEBSITE', 'REFERRAL', 'WALK_IN', 'SOCIAL_MEDIA', 'PROPERTY_PORTAL', 'COLD_CALL', 'EVENT', 'PARTNER_AGENT', 'ADVERTISEMENT', 'LEAD_CONVERSION', 'OTHER', name='customer_source_enum'), server_default='OTHER', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PROSPECT', 'BLACKLISTED', 'ARCHIVED', name='customer_status_enum'), server_default='ACTIVE', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_followup_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("aadhaar_number IS NULL OR aadhaar_number ~ '^[Xx]{4}-[Xx]{4}-[0-9]{4}$'", name=op.f('ck_customers_ck_customers_aadhaar_number_masked_format')),
    sa.CheckConstraint("pan_number IS NULL OR pan_number ~ '^[A-Z]{5}[0-9]{4}[A-Z]{1}$'", name=op.f('ck_customers_ck_customers_pan_number_format')),
    sa.CheckConstraint('annual_income IS NULL OR annual_income >= 0', name=op.f('ck_customers_ck_customers_annual_income_non_negative')),
    sa.CheckConstraint('budget_max IS NULL OR budget_max >= 0', name=op.f('ck_customers_ck_customers_budget_max_non_negative')),
    sa.CheckConstraint('budget_min IS NULL OR budget_max IS NULL OR budget_max >= budget_min', name=op.f('ck_customers_ck_customers_budget_max_gte_min')),
    sa.CheckConstraint('budget_min IS NULL OR budget_min >= 0', name=op.f('ck_customers_ck_customers_budget_min_non_negative')),
    sa.CheckConstraint('date_of_birth IS NULL OR date_of_birth <= created_at::date', name=op.f('ck_customers_ck_customers_dob_not_after_creation')),
    sa.CheckConstraint('postal_code IS NULL OR length(trim(postal_code)) > 0', name=op.f('ck_customers_ck_customers_postal_code_not_blank')),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_customers_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_customers_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_customers_lead_id_leads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_customers_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_assigned_to_id'), 'customers', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_customers_city'), 'customers', ['city'], unique=False)
    op.create_index(op.f('ix_customers_created_by_id'), 'customers', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_customers_customer_source'), 'customers', ['customer_source'], unique=False)
    op.create_index(op.f('ix_customers_customer_type'), 'customers', ['customer_type'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_lead_id'), 'customers', ['lead_id'], unique=False)
    op.create_index('ix_customers_name', 'customers', ['last_name', 'first_name'], unique=False)
    op.create_index(op.f('ix_customers_next_followup_date'), 'customers', ['next_followup_date'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_preferred_city'), 'customers', ['preferred_city'], unique=False)
    op.create_index(op.f('ix_customers_preferred_property_type'), 'customers', ['preferred_property_type'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_index(op.f('ix_customers_updated_by_id'), 'customers', ['updated_by_id'], unique=False)
    op.create_index('uq_customers_pan_number', 'customers', ['pan_number'], unique=True, postgresql_where=sa.text('pan_number IS NOT NULL'))
    op.create_index('uq_customers_passport_number', 'customers', ['passport_number'], unique=True, postgresql_where=sa.text('passport_number IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration's schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_customers_passport_number', table_name='customers', postgresql_where=sa.text('passport_number IS NOT NULL'))
    op.drop_index('uq_customers_pan_number', table_name='customers', postgresql_where=sa.text('pan_number IS NOT NULL'))
    op.drop_index(op.f('ix_customers_updated_by_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_preferred_property_type'), table_name='customers')
    op.drop_index(op.f('ix_customers_preferred_city'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_next_followup_date'), table_name='customers')
    op.drop_index('ix_customers_name', table_name='customers')
    op.drop_index(op.f('ix_customers_lead_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_type'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_source'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_by_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_city'), table_name='customers')
    op.drop_index(op.f('ix_customers_assigned_to_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_properties_uuid'), table_name='properties')
    op.drop_index('ix_properties_type_status_listing', table_name='properties')
    op.drop_index(op.f('ix_properties_state'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_code'), table_name='properties')
    op.drop_index('ix_properties_price', table_name='properties')
    op.drop_index(op.f('ix_properties_pincode'), table_name='properties')
    op.drop_index(op.f('ix_properties_listing_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_is_active'), table_name='properties')
    op.drop_index('ix_properties_city_state', table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_assigned_agent_id'), table_name='properties')
    op.drop_index('ix_properties_active_featured', table_name='properties')
    op.drop_table('properties')
    op.drop_index('ix_leads_status_priority', table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_priority'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_next_follow_up'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_full_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_by'), table_name='leads')
    op.drop_index('ix_leads_assigned_agent_id_status', table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_agent_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
